#!/bin/bash

# Decrypt file

if [[ ! -n $1 || -e $1 && ! -f $1 ]]; then
    echo "Please provide file to decrypt"
    exit
fi

if [[ -n $2 && -e $2 && ! -f $2 ]]; then
    echo "Please provide filename to store the encrypted content"
    exit
fi

OUTPUT=file.decrypted-`date +\%Y\%m\%d`

if [[ -n $2 ]]; then
    OUTPUT=$2
fi

openssl aes-256-cbc -d -a -in $1 -a -out $OUTPUT
